version: "3"
services:
  www:
    build: .
    ports:
      - 8001:80
    volumes:
      - ./:/var/www/html/
    links:
      - db
    networks:
      - default

  db:
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: osag
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: ''
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: ''
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
volumes:
  persistent:
